import {Platform} from 'react-native';

export const colors = {
    primary: '#4C9EEB',
    secondary: '#E9A6A6',
    aqua: '#77C8EB',
    thirdy: '#e7f5fe',
    background: '#E7ECF0',
    orange: '#FE930F',
    lightGray: '#A5A5A5',
    purple: '#724DBD',
    gray: '#424242',
    smoke: '#E6E6E6',
    white: '#ffffff',
    grey: '#A5A5A5',
    black: '#000000',
    placeholder: '#707070',
    blue: '#0d5cb6',
    red: '#E83625',
    green: '#088A08',
    lightGreen: '#59BC6C',
    yellow: '#FFDF00',
    bgInput: '#F6F6F6',
    borderInput: '#E8E8E8',
    textInput: '#C4C4C4',
    text: '#666666',
    border: '#CED5DC',
    bgSearch: '#E7ECF0',
    titleSearch: '#687684',
    bgSwitch: '#E9E9EA',
};

export const fonts = {
    sfProBold: 'SF-Pro-Display-Bold',
    sfPro: 'SF-Pro-Display-Regular',
    sfProThin: 'SF-Pro-Display-Thin',
    sfProBlack: 'SF-Pro-Display-Black',
    sfProSemiBold: 'SF-Pro-Display-Semibold',
    sfProLight: 'SF-Pro-Display-Light',
};