export const routes = {
  HOMESCREENS: 'HOMESCREENS',
  MESSAGESCREENS: 'MESSAGESCREENS',
  NOTIFICATIONSCREENS: 'NOTIFICATIONSCREENS',
  TRENDSCREENS: 'TRENDSCREENS',
  BOTTOMTABBAR: 'BOTTOMTABBAR',
  MESSAGESETTINGSCREENS: 'MESSAGESETTINGSCREENS',
  SEARCHSCREEN: 'SEARCHSCREEN',
  //DRAWER: 'DRAWER',
  };